### ISSUE TITLE
[Theme] Improvement CSS

### ISSUE THREAD

**Issue by DakinQuelia** [ThePix/QuestJS#40]
Hello,

I do several CSS tests.  Here is my result :

![defaulttheme](https://user-images.githubusercontent.com/420018/101820120-74d76000-3b26-11eb-8ee7-a269e3a73802.png)

A **default style**. We could make a function to call a custom CSS file.

What do you think ?

Best regards

**Comment by DakinQuelia** [comment]
New version !

![style](https://user-images.githubusercontent.com/420018/101857282-7117fd80-3b67-11eb-9bbf-576e64f13fbb.png)

**Comment by ThePix** [comment]
Looking good.

I have done an update that lets you set the CSS file in the settings. We could then add various versions to the basic game, and authors could choose a theme (maybe that is what you are thinking?).

**Comment by DakinQuelia** [comment]
Yes, I was thinking that.

I'll add my CSS version.

**Comment by DakinQuelia** [comment]
[style.zip](https://github.com/ThePix/QuestJS/files/5679707/style.zip)

**Comment by DakinQuelia** [comment]
I offer this function to add a custom CSS :

```
// Adding a custom CSS
function addCustomCSS(customCSS)
{
    if (!customCSS)
    {
        return;
    }
    
    document.writeln(`<link rel="stylesheet" href="game/${customCSS}.css" />`);
}
```

For example : ``addCustomCSS('filename')``

It's very useful if you want adding some CSS.

**Comment by ThePix** [comment]
A few queries about your default style. These things always sound negative, because I am only picking up on bits I disagree with so apologies for that!

Why `auto` rather than `scroll` for html overflow-y? I prefer scroll because it stops the screen changing once the text gets that long - and it will do so at some point.

The `body` element needs a background for users who upload to Itch.io, otherwise it will get set to grey.

You have no `h3` (admittedly I have no h2 or h4 either). `h3` is used for subtitle, should anyone use it.

Where is `qbtn` used?

When I use `showDropDown` or `showMenu` (in a conversation) the text is way to the left, under the side panes, and there is no dropdown as far as I can see.

A couple of classes have no dark mode:

* `a` links
* `.meta` messages
* `.menu-option`

**Comment by DakinQuelia** [comment]
I agree with that. I'll modify the CSS to fix the dark mode, background body and scolling. :)

**Comment by ThePix** [comment]
Do you think it would be better to have a style.css file in the lib folder as the game folder, and authors just put what they want to change in the latter? I have oscillated between the two, and cannot decide which would be best.

**Comment by DakinQuelia** [comment]
The better is :

- Get Style by default via "**lib folder**" (default.css) IF no style define in settings.
- If author define a new CSS File in "**game folder**" then using this file (with your code no change).
- If author define some CSS Files then using the addCustomCSS() function.

I think. :)

By example :

```
settings.styleFile = "myfile";
settings.customCSS = ["custom", "other"];
```

In this case the author define a style (global) and some CSS files (via array).

**Comment by DakinQuelia** [comment]
Have you got a screenshot for conversation, please ?

**Comment by ThePix** [comment]
Here:
![image](https://user-images.githubusercontent.com/9852110/102008117-1547a300-3d26-11eb-87f0-31a8008cc8d5.png)

If the screen is narrower, the side pane disappears and you can see it:
![Uploading image.png…]()

**Comment by DakinQuelia** [comment]
I'll fix it and will submit a new CSS File :)

**Comment by ThePix** [comment]
The problem was something I had done; sorry about that.

I have added the new file to Quest, but did tweak slightly. I also added the facility to add further CSS files in the way of themes. Authors can potentially pick one or more, to be used in addition to the default and their owncustomisation. If anyone fancies writing some CSS theme files...?

I will leave this open for now in case anything comes to light,

**Comment by DakinQuelia** [comment]
It's better. Good job. :) I'll note possibility of new ideas.

**Comment by ThePix** [comment]
Just updated it slightly so the text has a maximum width.

**Comment by DakinQuelia** [comment]
I suggest this :

```
#inner {
  max-width: 98%;
  margin:0 auto;
}
```

To adapt at screens.

**Comment by ThePix** [comment]
My thinking is that it is hard to read text  that is too wide. If someone has a wide screen and the browser is full screen, the text is easilt 40 cm wide, which is less convenient to read easily. A maximum size limits it.
https://baymard.com/blog/line-length-readability

**Comment by DakinQuelia** [comment]
I understand. But I prefer with pourcent instead of pixels.

**Comment by ThePix** [comment]
I am closing as I think it is resolved as far as possible.
