### ISSUE TITLE
Reimplementing OutputTextNoBr

### ISSUE THREAD

**Issue by bpetersonisme** [ThePix/QuestJS#65]
In Quest 5, there is a function called "OutputTextNoBr." It outputs a message as usual, but it omits the 'br,' allowing the NEXT message to be written on the same line. I want to re-implement this function in QuestJS, and I have something in mind that would allow it to work. This would allow for more compatibility when converting from Quest 5 to QuestJS, which I believe makes it worthwhile on its own. Additionally, that functionality would allow for more flexibility in game implementation moving forward. 

As far as I can tell, QuestJS doesn't have this functionality yet, but I wanted to make sure that I wasn't stepping on anybody's toes before I go trying to implement this.

**Comment by ThePix** [comment]
You are not stepping on toes.

It is not straightforward, as Quest 6 uses `<p>` to signify paragraphs, rather than `<br>`. You may want to look at the output queue, and add a code that tells it to wait until the next bit is there.

You might want to look here, if you have not already,
https://github.com/ThePix/QuestJS/wiki/Printing-Text#the-messaging-subsystem

**Comment by ThePix** [comment]
Closed, thanks to bpetersonisme for resolving

**Comment by bpetersonisme** [comment]
My pleasure! I've been looking over the code for a while, and I'm excited to actually start contributing directly.
