### ISSUE TITLE
Trouble With Tutorial

### ISSUE THREAD

**Issue by GoldenEagle75** [ThePix/QuestJS#78]
Hello, 
I am attempting to follow the tutorial in the wiki and I am getting errors with exits. The `Link` type exit generates an error and upon examination of the console I found out that it is apparently "not defined". 

I attempted to bypass this by creating exits the other way and then got to the locking section. The locking appears not to work either and also generates an error, saying that there is an unexpected identifier.

GoldenEagle75

**Comment by ThePix** [comment]
The issue with Link is that the documentation is ahead of the release. I have to update the docs as I go along otherwise I will lose track, to the docs reflect the up-to-the-minute changes, while releases can lag months behind.

So I have release 1.2, and that should hopefully resolve it.
https://github.com/ThePix/QuestJS/releases/tag/v1.2.0

Download the .zip, and copy across the files in lib, lang and rpg (if you use it); the rest should be fine.

I am not sure about the locking issue; let me know if that gets resolved too.

**Comment by GoldenEagle75** [comment]
Thank you! This fixed both problems.
