### ISSUE TITLE
Look Up, Down, N/S/E/W

### ISSUE THREAD

**Issue by thaskef** [ThePix/QuestJS#81]
Usually I look in certain directions when playing text adventures.  My Quest 5 games had descriptions for each direction someone might look to find something of interest.

Is there a way to implement that in QuestJS?

**Comment by ThePix** [comment]
Short answer: yes

It is worth adding to the library. Give me a few days and I will see what I can do. The attributes on the room objects will (almost certainly) be "look_east", "look_up", etc.

**Comment by ThePix** [comment]
I have added up update to github. You will need to update lang/lang-en.js and lib/_commands.js.

Docs are here:
https://github.com/ThePix/QuestJS/wiki/Attributes-for-rooms#look-directions

I will leave this open a couple of days in case you hit any issues.

**Comment by eliteinvestors** [comment]
Ok great it's working now as long as I create it as a function with a msg().  (It doesn't work with just a string.)

The only things to tidy up now are:
- if you look in a direction of a locked exit and there's no look-direction description, it throws an error.
- if you look in a direction where there isn't an exit and there's no look-direction description, it should probably say something like "You don't see anything of interest." (rather than "You can't go [direction].")

**Comment by ThePix** [comment]
Thanks, I have updated lib/_commands.js

**Comment by thaskef** [comment]
I was able to modify lang/lang-en.js as follows:
`  no_look_that_way:"{nv:char:can't:true} see anything of interest {show:dir}.",`

This resolved the second issue above.
